version: "2"

run:
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/VasySS/cloudru-load-balancer
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/VasySS/cloudru-load-balancer)

linters:
  settings:
    varnamelen:
      min-name-length: 2
      max-distance: 20
    nlreturn:
      # Size of the block (including return statement that is still "OK")
      # so no return split required.
      # Default: 1
      block-size: 2
    tagliatelle:
      case:
        use-field-name: true
        rules:
          json: goCamel

  default: all
  disable:
    # flaky
    - nolintlint
    - dupword
    - dupl
    - depguard
    - mnd
    - exhaustruct
    - funlen
    - varnamelen
    - containedctx
    - godox
