backends:
  - http://localhost:8081
  - http://localhost:8082

balancer:
  type: "least-connections"

rateLimit:
  type: "token-bucket"
  capacity: 100
  tokenRate: 10 # refill rate for token bucket and leak rate for leaky bucket
  refillInterval: 5s # for token bucket only
