backends:
  - http://localhost:8081
  - http://localhost:8082

balancer:
  type: "least-connections"
  backendsCheckInterval: 10s

rateLimit:
  type: "token-bucket"
  capacity: 100
  tokenRate: 10 # refill rate for token bucket and leak rate for leaky bucket
  tokenInterval: 5s # refill interval for token bucket and leak interval for leaky bucket
