// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	ratelimit "github.com/VasySS/cloudru-load-balancer/internal/ratelimit"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// SaveClient provides a mock function with given fields: ctx, client
func (_m *Repository) SaveClient(ctx context.Context, client ratelimit.ClientInfo) error {
	ret := _m.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for SaveClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ratelimit.ClientInfo) error); ok {
		r0 = rf(ctx, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
